reviews:
  request_changes_threshold: moderate
  approve_threshold: low
  ignore:
    - 'node_modules/**'
    - 'dist/**'
    - 'build/**'
    - '**/*.min.js'
    - '**/*.test.{js,jsx,ts,tsx}'
    - '**/__tests__/**'
    - '.next/**'
    - 'coverage/**'
  focus:
    - 'src/**'
  path_filters:
    - '!**/*.md'
    - '!**/*.lock'
  summarize: true
  summaries:
    required_changeset_size: small
  auto_review:
    enabled: true
    ignore_title_patterns:
      - 'WIP'
      - 'DO NOT MERGE'
    draft: false
    only_for_target_branch: false  # Enable auto reviews on all branches, not just the default
  labels:
    auto_assign: true
    add:
      needs-review: 'Changes require human review'
      ai-approved: 'CodeRabbit has approved these changes'
  assign:
    auto: true
