name: Test Only CI

on:
  push:
    branches:
      - main
      - feat/marvel
  pull_request:
    branches:
      - main
      - feat/marvel

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install dependencies
        run: pnpm install
      - name: Run tests with coverage
        run: pnpm run test --coverage
